# Generated by Django 5.0.6 on 2024-07-10 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Briefing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование инструктажа",
                        max_length=255,
                        verbose_name="Наименование инструктажа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Инструктаж",
                "verbose_name_plural": "Инструктажи",
            },
        ),
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chairman_name",
                    models.CharField(
                        help_text="Введите фамилию, имя и отчество председателя комиссии",
                        max_length=255,
                        verbose_name="ФИО председателя комиссии",
                    ),
                ),
                (
                    "chairman_position",
                    models.CharField(
                        help_text="Введите должность председателя комиссии",
                        max_length=255,
                        verbose_name="Должность председателя комиссии",
                    ),
                ),
                (
                    "member1_name",
                    models.CharField(
                        help_text="Введите фамилию, имя и отчество первого члена комиссии",
                        max_length=255,
                        verbose_name="ФИО первого члена комиссии",
                    ),
                ),
                (
                    "member1_position",
                    models.CharField(
                        help_text="Введите должность первого члена комиссии",
                        max_length=255,
                        verbose_name="Должность первого члена комиссии",
                    ),
                ),
                (
                    "member2_name",
                    models.CharField(
                        help_text="Введите фамилию, имя и отчество второго члена комиссии",
                        max_length=255,
                        verbose_name="ФИО второго члена комиссии",
                    ),
                ),
                (
                    "member2_position",
                    models.CharField(
                        help_text="Введите должность второго члена комиссии",
                        max_length=255,
                        verbose_name="Должность второго члена комиссии",
                    ),
                ),
                (
                    "safety_officer_name",
                    models.CharField(
                        help_text="Введите фамилию, имя и отчество ответственного за электробезопасность",
                        max_length=255,
                        verbose_name="ФИО ответственного за электробезопасность",
                    ),
                ),
                (
                    "safety_officer_position",
                    models.CharField(
                        help_text="Введите должность ответственного за электробезопасность",
                        max_length=255,
                        verbose_name="Должность ответственного за электробезопасность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комиссия",
                "verbose_name_plural": "Комиссии",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_number",
                    models.CharField(
                        help_text="Введите номер программы",
                        max_length=255,
                        verbose_name="Номер программы",
                    ),
                ),
                (
                    "course_name",
                    models.CharField(
                        help_text="Введите наименование программы",
                        max_length=255,
                        verbose_name="Наименование программы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Программа обучения",
                "verbose_name_plural": "Программы обучения",
                "ordering": ["course_number", "course_name"],
            },
        ),
        migrations.CreateModel(
            name="Examined",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Введите фамилию, имя и отчество проверяемого",
                        max_length=255,
                        verbose_name="ФИО проверяемого",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Введите должность проверяемого",
                        max_length=255,
                        verbose_name="Должность проверяемого",
                    ),
                ),
                (
                    "brigade",
                    models.CharField(
                        help_text="Введите участок или бригаду проверяемого",
                        max_length=255,
                        verbose_name="Участок (бригада) проверяемого",
                    ),
                ),
                (
                    "previous_safety_group",
                    models.CharField(
                        blank=True,
                        help_text="Предыдущая группа электробезопасности (обязательно при указании даты предыдущей проверки)",
                        max_length=255,
                        null=True,
                        verbose_name="Предыдущая группа электробезопасности",
                    ),
                ),
                (
                    "safety_group",
                    models.CharField(
                        help_text="Введите группу электробезопасности",
                        max_length=255,
                        verbose_name="Группа электробезопасности",
                    ),
                ),
                (
                    "work_experience",
                    models.CharField(
                        help_text="Введите стаж работы",
                        max_length=255,
                        verbose_name="Стаж работы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аттестуемый",
                "verbose_name_plural": "Аттестуемые",
                "ordering": ["brigade"],
            },
        ),
        migrations.CreateModel(
            name="Examination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время внесения записи о проверке (заполняется автоматически)",
                        verbose_name="Дата и время внесения записи",
                    ),
                ),
                (
                    "previous_check_date",
                    models.DateField(
                        blank=True,
                        help_text="Укажите дату предыдущей проверки",
                        null=True,
                        verbose_name="Дата проведения предыдущей проверки",
                    ),
                ),
                (
                    "current_check_date",
                    models.DateField(
                        help_text="Укажите дату текущей проверки",
                        verbose_name="Дата проведения текущей проверки",
                    ),
                ),
                (
                    "next_check_date",
                    models.DateField(
                        help_text="Укажите дату следующей проверки",
                        verbose_name="Дата проведения следующей проверки",
                    ),
                ),
                (
                    "protocol_number",
                    models.CharField(
                        help_text="Номер протокола проверки",
                        max_length=255,
                        verbose_name="Номер протокола проверки",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="Укажите причину проверки",
                        max_length=255,
                        verbose_name="Причина проверки",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        blank=True,
                        help_text="Введите номер удостоверения по специальности (при необходимости)",
                        max_length=255,
                        null=True,
                        verbose_name="Номер удостоверения по специальности",
                    ),
                ),
                (
                    "briefing",
                    models.ForeignKey(
                        help_text="Выберите вид инструктажа",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facility.briefing",
                        verbose_name="Инструктаж",
                    ),
                ),
                (
                    "commission",
                    models.ForeignKey(
                        help_text="Комиссия, проводящая проверку",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facility.commission",
                        verbose_name="Комиссия",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Выберите программу обучения",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facility.course",
                        verbose_name="Программа обучения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проверка",
                "verbose_name_plural": "Проверки",
                "ordering": ["current_check_date", "next_check_date"],
            },
        ),
    ]
