# Generated by Django 5.0.6 on 2024-06-27 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facility", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="examined",
            name="company_name",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите наименование компании",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.organization",
                verbose_name="Наименование компании",
            ),
        ),
        migrations.AddField(
            model_name="examined",
            name="user",
            field=models.ForeignKey(
                help_text="Пользователь, создавший запись",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="examination",
            name="examined",
            field=models.ForeignKey(
                help_text="Аттестуемый, проходящий проверку",
                on_delete=django.db.models.deletion.CASCADE,
                to="facility.examined",
                verbose_name="Аттестуемый",
            ),
        ),
    ]
