# Generated by Django 5.0.6 on 2024-06-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examination",
            name="current_check_date",
            field=models.DateField(
                help_text="Дата проведения текущей проверки",
                verbose_name="Дата проведения текущей проверки",
            ),
        ),
        migrations.AlterField(
            model_name="examination",
            name="next_check_date",
            field=models.DateField(
                help_text="Дата проведения следующей проверки",
                verbose_name="Дата проведения следующей проверки",
            ),
        ),
        migrations.AlterField(
            model_name="examination",
            name="previous_check_date",
            field=models.DateField(
                blank=True,
                help_text="Дата проведения предыдущей проверки",
                null=True,
                verbose_name="Дата проведения предыдущей проверки",
            ),
        ),
    ]
