# Generated by Django 5.0.6 on 2024-06-28 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facility", "0003_alter_examination_current_check_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examination",
            name="briefing",
            field=models.ForeignKey(
                help_text="Выберите вид инструктажа",
                on_delete=django.db.models.deletion.CASCADE,
                to="facility.briefing",
                verbose_name="Инструктаж",
            ),
        ),
        migrations.AlterField(
            model_name="examination",
            name="course",
            field=models.ForeignKey(
                help_text="Выберите программу обучения",
                on_delete=django.db.models.deletion.CASCADE,
                to="facility.course",
                verbose_name="Программа обучения",
            ),
        ),
        migrations.AlterField(
            model_name="examination",
            name="current_check_date",
            field=models.DateField(
                help_text="Укажите дату текущей проверки",
                verbose_name="Дата проведения текущей проверки",
            ),
        ),
        migrations.AlterField(
            model_name="examination",
            name="examined",
            field=models.ForeignKey(
                help_text="Введите данные аттестуемого",
                on_delete=django.db.models.deletion.CASCADE,
                to="facility.examined",
                verbose_name="Аттестуемый",
            ),
        ),
        migrations.AlterField(
            model_name="examination",
            name="next_check_date",
            field=models.DateField(
                help_text="Укажите дату следующей проверки",
                verbose_name="Дата проведения следующей проверки",
            ),
        ),
        migrations.AlterField(
            model_name="examination",
            name="previous_check_date",
            field=models.DateField(
                blank=True,
                help_text="Укажите дату предыдущей проверки",
                null=True,
                verbose_name="Дата проведения предыдущей проверки",
            ),
        ),
        migrations.AlterField(
            model_name="examination",
            name="reason",
            field=models.TextField(
                help_text="Укажите причину проверки", verbose_name="Причина проверки"
            ),
        ),
    ]
