# Generated by Django 5.0.6 on 2024-06-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "facility",
            "0004_alter_examination_briefing_alter_examination_course_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="examination",
            name="reason",
            field=models.CharField(
                help_text="Укажите причину проверки",
                max_length=255,
                verbose_name="Причина проверки",
            ),
        ),
    ]
